In [3]:
import torch

x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

max_val = x.max(dim=1)   # 默认 keepdim=False
print(max_val)
print(max_val.values)


max_val = x.max(dim=1, keepdim=True)
print(max_val)
print(max_val.values)

torch.return_types.max(
values=tensor([3, 6]),
indices=tensor([2, 2]))
tensor([3, 6])
torch.return_types.max(
values=tensor([[3],
        [6]]),
indices=tensor([[2],
        [2]]))
tensor([[3],
        [6]])


In [6]:
x = torch.tensor([[1., 2., 3.]])
print(x)       # ok
  # -> tensor(3.)  shape []
print(x.max(dim=-1).values)       # ok
  
print(x - 3.)       # ok

tensor([[1., 2., 3.]])
tensor([3.])
tensor([[-2., -1.,  0.]])
